### ISSUE TITLE
PopupBackgroundStyle

### ISSUE THREAD

**Issue by MattiaConfalonieri** [daisuke310vvv/PopupController#14]
BlackFilter(alpha: CGFloat) not work.

in slide up animation there is

                self.baseScrollView.backgroundColor = UIColor.blackColor().colorWithAlphaComponent(0.7)

instead

                self.baseScrollView.backgroundColor = UIColor.blackColor().colorWithAlphaComponent(alpha)

**Comment by daisuke310vvv** [comment]
@MattiaConfalonieri Thank you for your issue.
I'd like to fix it asap!
